// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamp
}

type PrintRequest struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ServiceVariantID pgtype.UUID
	CustomerName     string
	Phone            string
	Notes            pgtype.Text
	Copies           int32
	PaperSize        string
	ColorMode        string
	DeliveryType     string
	DueDate          pgtype.Timestamp
	Status           string
	FileUrl          string
	PaymentProofUrl  string
	InvoiceNumber    string
	TotalPrice       int64
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type RequestStatusLog struct {
	ID             pgtype.UUID
	PrintRequestID pgtype.UUID
	OldStatus      pgtype.Text
	NewStatus      string
	ChangedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamp
}

type Service struct {
	ID           pgtype.UUID
	CategoryID   pgtype.UUID
	Name         string
	Slug         string
	Description  pgtype.Text
	ThumbnailUrl pgtype.Text
	Active       pgtype.Bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type ServiceVariant struct {
	ID        pgtype.UUID
	ServiceID pgtype.UUID
	Name      string
	PaperSize string
	ColorMode string
	Price     int64
	Active    pgtype.Bool
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	FullName  string
	Phone     pgtype.Text
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
