// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: print_requests.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrintRequest = `-- name: CreatePrintRequest :one
INSERT INTO print_requests (
    user_id,
    service_variant_id,
    customer_name,
    phone,
    notes,
    copies,
    paper_size,
    color_mode,
    delivery_type,
    due_date,
    status,
    file_url,
    payment_proof_url,
    invoice_number,
    total_price
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10,
           $11,
           $12,
           $13,
           $14,
           $15
       )
    RETURNING id, user_id, service_variant_id, customer_name, phone, notes, copies, paper_size, color_mode, delivery_type, due_date, status, file_url, payment_proof_url, invoice_number, total_price, created_at, updated_at
`

type CreatePrintRequestParams struct {
	UserID           pgtype.UUID
	ServiceVariantID pgtype.UUID
	CustomerName     string
	Phone            string
	Notes            pgtype.Text
	Copies           int32
	PaperSize        string
	ColorMode        string
	DeliveryType     string
	DueDate          pgtype.Timestamp
	Status           string
	FileUrl          string
	PaymentProofUrl  string
	InvoiceNumber    string
	TotalPrice       int64
}

func (q *Queries) CreatePrintRequest(ctx context.Context, arg CreatePrintRequestParams) (PrintRequest, error) {
	row := q.db.QueryRow(ctx, createPrintRequest,
		arg.UserID,
		arg.ServiceVariantID,
		arg.CustomerName,
		arg.Phone,
		arg.Notes,
		arg.Copies,
		arg.PaperSize,
		arg.ColorMode,
		arg.DeliveryType,
		arg.DueDate,
		arg.Status,
		arg.FileUrl,
		arg.PaymentProofUrl,
		arg.InvoiceNumber,
		arg.TotalPrice,
	)
	var i PrintRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceVariantID,
		&i.CustomerName,
		&i.Phone,
		&i.Notes,
		&i.Copies,
		&i.PaperSize,
		&i.ColorMode,
		&i.DeliveryType,
		&i.DueDate,
		&i.Status,
		&i.FileUrl,
		&i.PaymentProofUrl,
		&i.InvoiceNumber,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrintRequests = `-- name: GetPrintRequests :many
SELECT id, user_id, service_variant_id, customer_name, phone, notes, copies, paper_size, color_mode, delivery_type, due_date, status, file_url, payment_proof_url, invoice_number, total_price, created_at, updated_at FROM print_requests
ORDER BY created_at DESC
`

func (q *Queries) GetPrintRequests(ctx context.Context) ([]PrintRequest, error) {
	rows, err := q.db.Query(ctx, getPrintRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrintRequest
	for rows.Next() {
		var i PrintRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceVariantID,
			&i.CustomerName,
			&i.Phone,
			&i.Notes,
			&i.Copies,
			&i.PaperSize,
			&i.ColorMode,
			&i.DeliveryType,
			&i.DueDate,
			&i.Status,
			&i.FileUrl,
			&i.PaymentProofUrl,
			&i.InvoiceNumber,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrintRequestsByUser = `-- name: GetPrintRequestsByUser :many
SELECT id, user_id, service_variant_id, customer_name, phone, notes, copies, paper_size, color_mode, delivery_type, due_date, status, file_url, payment_proof_url, invoice_number, total_price, created_at, updated_at FROM print_requests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPrintRequestsByUser(ctx context.Context, userID pgtype.UUID) ([]PrintRequest, error) {
	rows, err := q.db.Query(ctx, getPrintRequestsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrintRequest
	for rows.Next() {
		var i PrintRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceVariantID,
			&i.CustomerName,
			&i.Phone,
			&i.Notes,
			&i.Copies,
			&i.PaperSize,
			&i.ColorMode,
			&i.DeliveryType,
			&i.DueDate,
			&i.Status,
			&i.FileUrl,
			&i.PaymentProofUrl,
			&i.InvoiceNumber,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrintRequestStatus = `-- name: UpdatePrintRequestStatus :one
UPDATE print_requests
SET status = $2,
    updated_at = NOW()
WHERE id = $1
    RETURNING id, user_id, service_variant_id, customer_name, phone, notes, copies, paper_size, color_mode, delivery_type, due_date, status, file_url, payment_proof_url, invoice_number, total_price, created_at, updated_at
`

type UpdatePrintRequestStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdatePrintRequestStatus(ctx context.Context, arg UpdatePrintRequestStatusParams) (PrintRequest, error) {
	row := q.db.QueryRow(ctx, updatePrintRequestStatus, arg.ID, arg.Status)
	var i PrintRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceVariantID,
		&i.CustomerName,
		&i.Phone,
		&i.Notes,
		&i.Copies,
		&i.PaperSize,
		&i.ColorMode,
		&i.DeliveryType,
		&i.DueDate,
		&i.Status,
		&i.FileUrl,
		&i.PaymentProofUrl,
		&i.InvoiceNumber,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
