// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    category_id,
    name,
    slug,
    description,
    thumbnail_url
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
    RETURNING id, category_id, name, slug, description, thumbnail_url, active, created_at, updated_at
`

type CreateServiceParams struct {
	CategoryID   pgtype.UUID
	Name         string
	Slug         string
	Description  pgtype.Text
	ThumbnailUrl pgtype.Text
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ThumbnailUrl,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT id, category_id, name, slug, description, thumbnail_url, active, created_at, updated_at FROM services
WHERE slug = $1
    LIMIT 1
`

func (q *Queries) GetServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServices = `-- name: GetServices :many
SELECT id, category_id, name, slug, description, thumbnail_url, active, created_at, updated_at FROM services
ORDER BY created_at DESC
`

func (q *Queries) GetServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ThumbnailUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
