// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_variants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceVariant = `-- name: CreateServiceVariant :one
INSERT INTO service_variants (
    service_id,
    name,
    paper_size,
    color_mode,
    price
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
    RETURNING id, service_id, name, paper_size, color_mode, price, active, created_at
`

type CreateServiceVariantParams struct {
	ServiceID pgtype.UUID
	Name      string
	PaperSize string
	ColorMode string
	Price     int64
}

func (q *Queries) CreateServiceVariant(ctx context.Context, arg CreateServiceVariantParams) (ServiceVariant, error) {
	row := q.db.QueryRow(ctx, createServiceVariant,
		arg.ServiceID,
		arg.Name,
		arg.PaperSize,
		arg.ColorMode,
		arg.Price,
	)
	var i ServiceVariant
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.PaperSize,
		&i.ColorMode,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantsByService = `-- name: GetVariantsByService :many
SELECT id, service_id, name, paper_size, color_mode, price, active, created_at FROM service_variants
WHERE service_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetVariantsByService(ctx context.Context, serviceID pgtype.UUID) ([]ServiceVariant, error) {
	rows, err := q.db.Query(ctx, getVariantsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceVariant
	for rows.Next() {
		var i ServiceVariant
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.PaperSize,
			&i.ColorMode,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
