name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        shell: cmd
        run: go mod tidy

      - name: Build
        run: go build -o app.exe ./cmd/api

      - name: Stop service
        continue-on-error: true
        shell: cmd
        run: net stop PrintingShopAPI

      - name: Copy binary
        run: copy app.exe D:\CodeBase\printing-shop-api\app.exe

      - name: Start service
        shell: cmd
        run: net start PrintingShopAPI